const PRODUCTS = [
  {
    nama: "Sistem Automation PDF",
    kategori: "berbayar",
    tipe: "Produk Digital",
    deskripsi: "Solusi praktis untuk membantu kontrol jobdesk dan alur kerja dengan pendekatan yang lebih sistematis. Cocok untuk yang ingin mulai membangun kerja berbasis sistem.",
    gambar: "https://res.cloudinary.com/dilamvetq/image/upload/v1775504554/copy_of_iv3x53tl4mzhhj9aacy1_dfb6b8.png",
    harga: "Rp 149.000",
    hargaCoret: "Rp 299.000",
    tombol: "Beli di Lynk.id",
    link: "https://lynk.id/kerjadengansistem",
    badge: "BEST SELLER",
    warna: "biru",
    ikon: "web"
  },
  {
    nama: "Produk & Resource di Lynk.id",
    kategori: "berbayar",
    tipe: "Store Hub",
    deskripsi: "Pintu masuk utama untuk melihat penawaran, produk digital, dan resource yang dijual dalam satu tempat yang lebih rapi.",
    gambar: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=1200&q=80",
    harga: "Mulai dari produk aktif",
    hargaCoret: "",
    tombol: "Buka Lynk.id",
    link: "https://lynk.id/kerjadengansistem",
    badge: "TOKO RESMI",
    warna: "ungu",
    ikon: "artikel"
  },
  {
    nama: "Akses Produk Digital",
    kategori: "berbayar",
    tipe: "Checkout Cepat",
    deskripsi: "Untuk pengunjung yang sudah siap membeli, homepage ini sekarang langsung mengarahkan ke jalur checkout dan halaman penjualan utama Bos.",
    gambar: "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200&q=80",
    harga: "Checkout via Lynk.id",
    hargaCoret: "",
    tombol: "Lihat Penawaran",
    link: "https://lynk.id/kerjadengansistem",
    badge: "AKSES INSTAN",
    warna: "cyan",
    ikon: "robot"
  },
  {
    nama: "Blog AI & Automation",
    kategori: "gratis",
    tipe: "Resource Gratis",
    deskripsi: "Kumpulan artikel edukasi untuk memahami AI, chatbot, workflow, dan automation bisnis secara lebih runtut sebelum memutuskan membeli produk.",
    gambar: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Blog",
    link: "https://artikel.kerjadengansistem.web.id/",
    badge: "UPDATE HARIAN",
    warna: "hijau",
    ikon: "artikel"
  },
  {
    nama: "Panduan AI Agent untuk Bisnis",
    kategori: "gratis",
    tipe: "Artikel Gratis",
    deskripsi: "Pengantar yang lebih jelas tentang AI agent dan mengapa pendekatan ini mulai dipakai dalam operasional bisnis modern.",
    gambar: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Sekarang",
    link: "https://artikel.kerjadengansistem.web.id/artikel/apa-itu-ai-agent-dan-kenapa-bisnis-mulai-memakainya.html",
    badge: "POPULER",
    warna: "oranye",
    ikon: "robot"
  },
  {
    nama: "Panduan Membangun Chatbot AI",
    kategori: "gratis",
    tipe: "Artikel Gratis",
    deskripsi: "Artikel praktis untuk memahami cara membangun chatbot AI yang benar-benar berguna bagi kebutuhan bisnis.",
    gambar: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Sekarang",
    link: "https://artikel.kerjadengansistem.web.id/artikel/membangun-chatbot-ai-untuk-bisnis.html",
    badge: "PRAKTIS",
    warna: "pink",
    ikon: "kode"
  }
];
