const PRODUCTS = [
  {
    nama: "Dashboard Keuangan",
    kategori: "berbayar",
    tipe: "Web App",
    deskripsi: "Web app dashboard keuangan untuk membantu memantau ringkasan keuangan, membaca pergerakan data, dan melihat kondisi bisnis dengan tampilan yang lebih rapi dan mudah dipahami.",
    gambar: "https://res.cloudinary.com/dilamvetq/image/upload/v1777495062/copy_of_fkg6inffi8w2wfq3nxmr_dd183d.png",
    harga: "Produk Digital",
    hargaCoret: "",
    tombol: "Pelajari Lebih Lanjut",
    link: "https://dashboardkeuangan.lp.biver.id",
    badge: "PRODUK UTAMA",
    warna: "biru",
    ikon: "web"
  },
  {
    nama: "Blog AI & Automation",
    kategori: "gratis",
    tipe: "Resource Gratis",
    deskripsi: "Kumpulan artikel edukasi untuk memahami AI, chatbot, workflow, dan automation bisnis secara lebih runtut sebelum melanjutkan ke produk.",
    gambar: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Blog",
    link: "https://artikel.kerjadengansistem.web.id/",
    badge: "UPDATE HARIAN",
    warna: "hijau",
    ikon: "artikel"
  },
  {
    nama: "Panduan AI Agent untuk Bisnis",
    kategori: "gratis",
    tipe: "Artikel Gratis",
    deskripsi: "Pengantar yang lebih jelas tentang AI agent dan mengapa pendekatan ini mulai dipakai dalam operasional bisnis modern.",
    gambar: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Sekarang",
    link: "https://artikel.kerjadengansistem.web.id/artikel/apa-itu-ai-agent-dan-kenapa-bisnis-mulai-memakainya.html",
    badge: "POPULER",
    warna: "oranye",
    ikon: "robot"
  },
  {
    nama: "Panduan Membangun Chatbot AI",
    kategori: "gratis",
    tipe: "Artikel Gratis",
    deskripsi: "Artikel praktis untuk memahami cara membangun chatbot AI yang benar-benar berguna bagi kebutuhan bisnis.",
    gambar: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Sekarang",
    link: "https://artikel.kerjadengansistem.web.id/artikel/membangun-chatbot-ai-untuk-bisnis.html",
    badge: "PRAKTIS",
    warna: "pink",
    ikon: "kode"
  },
  {
    nama: "Tools Automation 2026",
    kategori: "gratis",
    tipe: "Artikel Gratis",
    deskripsi: "Rekomendasi tools automation yang relevan untuk workflow, lead handling, dan sistem kerja yang lebih efisien.",
    gambar: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Sekarang",
    link: "https://artikel.kerjadengansistem.web.id/artikel/tools-automation-yang-wajib-dikuasai-2026.html",
    badge: "WAJIB BACA",
    warna: "cyan",
    ikon: "petir"
  },
  {
    nama: "Machine Learning untuk Pemula",
    kategori: "gratis",
    tipe: "Artikel Gratis",
    deskripsi: "Penjelasan dasar machine learning yang lebih mudah dipahami untuk pembaca umum dan pelaku bisnis.",
    gambar: "https://images.unsplash.com/photo-1555255707-c07966088b7b?w=1200&q=80",
    harga: "GRATIS",
    hargaCoret: "",
    tombol: "Baca Sekarang",
    link: "https://artikel.kerjadengansistem.web.id/artikel/panduan-machine-learning-untuk-pemula.html",
    badge: "PEMULA",
    warna: "ungu",
    ikon: "grafik"
  }
];
